theme: minima
title: My Doc
author: Mahesh GitHub User
email: mahesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  i have made this changes to test my training
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
